#!/bin/bash

emojis=(                           进)

len=${#emojis[@]}

len=$((len - 1))
#ts=`date +%S`

#pos=$((ts % len))
pos=`shuf -i 0-$len -n 1`
echo -n ${emojis[$pos]}
